### ISSUE TITLE
segfault in hlsl example in validation layer

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/vulkan#220]
Could be this: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2217, this issue is a reminder for me to resolve this.

only happens when `VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT` is enabled

```
Thread 1 "hlsl" received signal SIGSEGV, Segmentation fault.
0x00007fff8a372364 in ?? ()
   from /nix/store/dkpjsm1cz1fl9zda66vhy8g9l4ixpbir-nvidia-x11-455.46.02-5.4.78/lib/libnvidia-glcore.so.455.46.02
(gdb) bt
#0  0x00007fff8a372364 in ?? ()
   from /nix/store/dkpjsm1cz1fl9zda66vhy8g9l4ixpbir-nvidia-x11-455.46.02-5.4.78/lib/libnvidia-glcore.so.455.46.02
#1  0x00007fff4f59e10b in DispatchCmdBindDescriptorSets(VkCommandBuffer_T*, VkPipelineBindPoint, VkPipelineLayout_T*, unsigned int, unsigned int, VkDescriptorSet_T* const*, unsigned int, unsigned int const*) ()
   from /nix/store/p3ss3a6mmaglyghcs82dhd4308r7fjf2-vulkan-validation-layers-1.2.141.0/lib/libVkLayer_khronos_validation.so
#2  0x00007fff4f861f28 in DebugPrintf::AllocateDebugPrintfResources(VkCommandBuffer_T*, VkPipelineBindPoint) ()
   from /nix/store/p3ss3a6mmaglyghcs82dhd4308r7fjf2-vulkan-validation-layers-1.2.141.0/lib/libVkLayer_khronos_validation.so
#3  0x00007fff4f4dcdcf in vulkan_layer_chassis::CmdDraw(VkCommandBuffer_T*, unsigned int, unsigned int, unsigned int, unsigned int) ()
   from /nix/store/p3ss3a6mmaglyghcs82dhd4308r7fjf2-vulkan-validation-layers-1.2.141.0/lib/libVkLayer_khronos_validation.so
#4  0x000000000043ac07 in ?? () at hlsl/Render.hs:125
#5  0x0000000000000000 in ?? ()
```

in `vkCmdDraw`

**Comment by expipiplus1** [comment]
Still happens with 1.2.162 validation layers

**Comment by expipiplus1** [comment]
and 1.2.182
